language: dart
dart:
  - '2.7.0'
notifications: {email: false}
install:
  - pub global activate coveralls 5.7.0
  - pub global activate coverage 0.13.8
script:
  - set -e
  - pub get
  # Run dartanalyzer.
  - dartanalyzer --fatal-warnings ./
  # Start tests.
  - pub run test test/test_all.dart --reporter expanded
  - dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit test/test_all.dart &
  - echo "Collecting test coverage on port 8111"
  # Run the coverage collector to generate the JSON coverage report.
  - nohup pub global run coverage:collect_coverage --port=8111 --out=var/coverage.json --wait-paused --resume-isolates
  # Convert the JSON coverage report to LCOV report.
  - echo "Generating LCOV report..."
  - pub global run coverage:format_coverage --lcov --in=var/coverage.json --out=var/lcov.info --packages=.packages --report-on=lib
after_success:
  # Submit LCOV reports to Codecov.
  - bash <(curl -s https://codecov.io/bash)

# Disable dart tasks. We're using ./tool/travis.sh to perform tests.
# dart_task:
#   - test: --platform vm # Dart VM
#   - dartanalyzer: true
