language: dart
dart:
  - stable
notifications: {email: false}
before_install:
  - chmod +x ./tool/travis.sh
install:
  - pub global activate coveralls
  - pub global activate coverage
script: ./tool/travis.sh
env:
  - DARTANALYZER_FLAGS=--fatal-warnings

# Uploading LCOV to Coveralls is handled inside travis.sh
# after_success:
#  - coveralls var/lcov.info

# Disable dart tasks. We're using ./tool/travis.sh to perform tests.
# dart_task:
#   - test: --platform vm # Dart VM
#   - dartanalyzer: true