language: dart
dart:
  - '2.2.0'
# Coverage is currently broken for dart version 2.3.0 and above.
# Using version 2.2.0 to run the tests for now.
# Source: https://github.com/dart-lang/coverage/issues/249
notifications: {email: false}
before_install:
  - chmod +x ./tool/travis.sh
install:
  - pub global activate coveralls
  - pub global activate coverage
script: ./tool/travis.sh
after_success:
  - coveralls var/lcov.info
env:
  - DARTANALYZER_FLAGS=--fatal-warnings

# Uploading LCOV to Coveralls is handled inside travis.sh
# after_success:
#  - coveralls var/lcov.info

# Disable dart tasks. We're using ./tool/travis.sh to perform tests.
# dart_task:
#   - test: --platform vm # Dart VM
#   - dartanalyzer: true
