language: dart
dart:
  - stable
notifications: {email: false}
install:
  - pub global activate coveralls
  - pub global activate coverage
script: ./tool/travis.sh
after_success:
  - coveralls var/lcov.info
env:
  - DARTANALYZER_FLAGS=--fatal-warnings

# Disable dart tasks. We're using ./tool/travis.sh to perform tests.
# dart_task:
#   - test: --platform vm # Dart VM
#   - dartanalyzer: true