codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "lib/src/core/crypto/catapultnacl.dart"
  - "lib/src/infrastructure/model/**/*"
