name: nem2_sdk_dart
author: Fajar van Megen
description: A software development kit (SDK) for building NEM2 applications with Dart
# TODO insert a link to homepage/docs/dart pub packages e.g. https://pub.dartlang.org/packages/nem2-sdk-dart
# documentation: http://nem2-sdk-dart.github.io/docs/
homepage: https://github.com/fajarvm/nem2-sdk-dart
version: 0.5.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  fixnum: ^0.10.9
  pointycastle: ^1.0.1
  encrypt: ^2.0.0

dev_dependencies:
  test: ^1.5.3
