name: nem2_sdk_dart
version: 0.1.0
author: Fajar van Megen

description: A NEM2 Software Development Kit (SDK) for building applications with Dart
# TODO insert a link to homepage/docs/dart pub packages e.g. https://pub.dartlang.org/packages/nem2-sdk-dart
# documentation: http://nem2-sdk-dart.github.io/docs/
homepage: https://github.com/fajarvm/nem2-sdk-dart
issue_tracker: https://github.com/fajarvm/nem2-sdk-dart/issues
repository: https://github.com/fajarvm/nem2-sdk-dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  fixnum: ^0.10.11
  pointycastle: ^1.0.1
  encrypt: ^3.3.1

dev_dependencies:
  test: ^1.9.3
  # Enable these dependencies when not using the global library
  # coveralls: ^5.6.0
  # coverage: ^0.13.3
