name: symbol_sdk_dart
version: 0.1.0
author: Fajar van Megen

description: A Software Development Kit (SDK) for Symbol blockchain to build applications with Dart
# TODO insert a link to homepage/docs/dart pub packages e.g. https://pub.dartlang.org/packages/symbol-sdk-dart
# documentation: http://symbol-sdk-dart.github.io/docs/
homepage: https://github.com/fajarvm/symbol-sdk-dart
issue_tracker: https://github.com/fajarvm/symbol-sdk-dart/issues
repository: https://github.com/fajarvm/symbol-sdk-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  fixnum: ^0.10.11
  tweetnacl: ^0.3.2
  pointycastle:
    git: https://github.com/fajarvm/pc-dart.git
  encrypt:
    git: https://github.com/fajarvm/encrypt.git

dev_dependencies:
  test: ^1.12.0
  # Enable these dependencies when not using the global library
  # coveralls: ^5.7.0
  # coverage: ^0.13.8
