language: dart
dart:
  - "2.1.0"
dart_task:
  # Dart VM
  - test: --platform vm
  # Chrome browser
  # - test: --platform chrome
  # Chrome with Dart VM. Use either this or Chrome, not both.
  # - test: --platform dartium
  # install_dartium: true

  ################################
  # Examples of some other tasks #
  ################################
  #
  # Dart Formatter
  # Checks for code formatting conforms dartfmt.
  # - dartfmt
  #
  # Dart Analyzer
  # Warnings are fatal, but we only analyze the lib/ directory.
  # - dartanalyzer: --fatal-warnings lib
  #
  # XVFB (Virtual Framebuffer X Server for X)
  # On Linux, the test runner uses XVFB by default so that it can use browsers like Chrome that require a display.
  # However, this may interfere with certain applications, so you can turn it off by setting xvfb: false either at
  # the top level or for a particular task.
  # - test: --exclude-tags no-xvfb
  # xvfb: false
